sudo: false
cache: bundler
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby
  - ruby-head
gemfile:
  - gemfiles/active_support_5.0.gemfile
  - gemfiles/active_support_6.0.gemfile
before_install:
  - "rm -f ${BUNDLE_GEMFILE}.lock"
matrix:
  fast_finish: true
  exclude:
    - rvm: jruby
      gemfile: gemfiles/active_support_5.0.gemfile
    - rvm: 2.2.9
      gemfile: gemfiles/active_support_6.0.gemfile
    - rvm: 2.3.6
      gemfile: gemfiles/active_support_6.0.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/active_support_6.0.gemfile
  allow_failures:
    - rvm: ruby-head
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rails-contrib"
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "HnqK+r2/SLv2Z1XMkL0oNO0w/xaUn9cGHpr2mGDNnk+SUz1XBO2bu5c0ykyAVnLienFPCDExX3RYwTMNvC4AhkAR8DK0v4FD+0g/dMy2j1wGzQlNtqF2B4EbRpVpZtmM3hK6dDNRR3V/zipqTkut00PoFPp/Bzm7DoH/w/MIPBY="
